### ISSUE TITLE
two possible improvements for vasculature datasets

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#155]
It would be nice to have the following two features in MorphIO, related to working with vasculature datasets and blood flow simulations

1) #### File format
The original data for vasculatures is in .vtk format, with two tables:
- list of points
- list of segments with radii associated with them

This format seems not compatible with the hdf5 files red by MorphIO, as they have radii values on points. The conversion from vtk to hdf5, therefore, modifies the original data. In addition, it is not invertible, i.e. one cannot go back fro hdf5 to the original vtk. 

Reading the hdf5 vasculature doc a bit more carefully, ([https://bbpteam.epfl.ch/documentation/projects/Morphology%20Documentation/latest/h5vasculature.html](url)) I noticed the optional group/property, which can assign any values on points, segments or sections.

So here is a possible option to solve this. We can use this additional section of the hdf5 format to save the original radii on segments so that we are faithful to the original datasets. 

In addition, for blood flow simulations, some results will be on segments (blood flow) or points (blood pressure), and possibly time/frequency-dependent. This implies that multiple columns should be available for points and segment optional array. 

2) #### Connectivity format 
If MorphIO could load the hdf5 format into a connectivity graph based on points, rather than sections, possibly of the same format as in vtk files, i.e. list of points (same as in hdf5), and list of segments (two points ids per segment), with corresponding radii (taken from the original data, see point above), or any other values.

**Comment by eleftherioszisis** [comment]
**1. File format**

The vtk format of the vasculature is an external non-standard format. It was provided to us and there is no guaranty that the same spec will be provided in the future or from another lab.

The hdf5 vasculature spec is a natural extension of the h5v1 tree representation for cells to allow for loops. A section is a continuous chain of points and radii that can be decomposed into truncated and spatially continuous cones. Using radii on the edges leads to a non-continuous geometrical structure.

For the purposes of the simulation, given that you have points and edges why not just use the average of the edge's points?

Concerning the results. The geometry datasets incorporate static information that doesn't change. Therefore, adding simulation results as properties will requires to copy the whole dataset every time. Instead of mixing structural and functional components into one format, we should create a spec that represents the simulation data and which refers to a structural vasculature dataset. This why we can have the structure and multiple simulation data on the shame geometry.

**2. Connectivity Format**

It would be useful to be able able to retrieve the point connectivity of the morphology. However, we decide how duplicate points are going to affect the point connectivity and what is the desired result.

**Comment by arnaudon** [comment]
#### 1)

This is the issue in pictures. For blood flow simulations, we need segments with constant radii, for computational reasons, so if we do the following processing of the data, we are not really using the original dataset (for that dataset of course). I won't make the decision on what should be used/is better/correct, etc... I'm just pointing it out here:

![vasculature_morphio_issue](https://user-images.githubusercontent.com/12429955/73450799-73fe6b00-4366-11ea-8201-63aaad13c6a8.png)

#### 2)

A homemade version of the converter exists, but it would be nice to have an official one on morphio.

**Comment by eleftherioszisis** [comment]
1) The diagram is correct indeed. There is a transformation that affects the interpolation of values in the branching points. This is the geometry representation that is used throughout the circuit building pipeline (middle).

We could devise a smarter approach on how to calculate the edge radii on the branching points  if this is introducing a significant error in your results.

2) The vtk data file does not have a spec, therefore shouldn't be supported by MorphIO's reading and writing. Maybe these scripts could be available through a general vasculature api package that uses MorphIO.

**Comment by arnaudon** [comment]
This discussion is outdated, we have working solution elsewhere.
