### ISSUE TITLE
Add CMAKE flag for disabling unifurcation sanitization

### ISSUE THREAD

**Issue by alexsavulescu** [BlueBrain/MorphIO#175]
Following a discussion with @mgeplf the other day, I think it may be worth it to temporarily add a CMAKE flag to disable the unifurcation sanitization to be able to easily work with circuits that already have them (and until the edges and morphologies in those circuits get updated). 

What do you think @mgeplf ?

**Comment by mgeplf** [comment]
I've been on the fence about this for a while - having a mode where the morphology is represented exactly it is on disk would be useful (ie: no sanitization) but the problem is that we need to take this pain, since some of the representations aren't compatible with single children - namely SWC.

As such, this is a can of worms I'd prefer not opening at this point.  However, I'm open to being convinced.  What do you think @wizmer?

**Comment by lidakanari** [comment]
Allowing unifurcations is a bit dangerous in the context of morphologies. I am not sure what the impact is for neuronal functionality, but there are issues associated to structural analysis. Namely, some file formats (SWC) cannot support unifurcations. Therefore, the same cell in different formats (SWC, ASC, H5) will have different section indexing (as well as different total number of sections and all related measurements). So all analysis, will depend on the file format. This issue breaks continuity and consistency for biological datasets, and from our point of view it is considered a _reconstruction error_ that the labs need to correct before we accept their data.

**Comment by wizmer** [comment]
A bit in the continuity of Lida's comment. I think not correcting the unifurcation is just delaying the point of failure later in the pipeline. We don't really know how the various software behave with unifurcation so it's a bit problematic. And yes, the fact that it creates a mismatch in section ID between SWC and ASC/H5 is also problematic.

The problem is that we have been building circuits with unsanitized data in the past. We need to take actions internally so that it does not happen again. I'll try to think about it on my side, I don't have any solution right now.

**Comment by alexsavulescu** [comment]
To give you a bit of context: I'm working on a way to use MorphIO for morphology loading (to support H5 but also ASC/SWC). For me this would be just temporary, for "read" purposes only, and it would be set to False by default, like if you know you are doing simulations on a circuit with unifurcations, then you set up your MorphIO like that so you can use the new solution.

**Comment by wizmer** [comment]
Disabling unifurcation is a feature that has been asked multiple times so I can't really ignore it. However, I think it is a double edge sword, since it is just postponing the problem.
For that reason I will create a branch with an additional opening flag: `no-sanitize` 
However I do not plan to merge this branch into master at any point. Let's consider this branch only useful for checking things.

**Comment by wizmer** [comment]
The branch is available there:
https://github.com/BlueBrain/MorphIO/tree/no-sanitize

```c++
auto m = morphio::Morphology("sample.asc",  options=morphio::NO_SANITIZE);
```
Allows you to open the file without any sanitization.
This means, it does not merge unifurcations but it also does not add missing duplicate points (ie. the first point of a section should in principle be the last point of the parent section).

**Comment by alexsavulescu** [comment]
Thank you @wizmer

**Comment by asanin-epfl** [comment]
section mapping can be got with usual MorphIO:
```
def _get_merged_section_ids_map(m: Morphology):
    annotations = [annotation for annotation in m.annotations if
            annotation.type == AnnotationType.single_child]
    original_section_num = len(annotations) + len(m.sections)
    merged_section_ids_map = OrderedDict({i: i for i in range(original_section_num)})
    merged_sections_annotations = []
    for annotation in annotations:
        merged_sections_annotations.append(annotation)
        merged_id = annotation.section_id
        for i in range(merged_id, len(merged_section_ids_map)):
            merged_section_ids_map[i] -= 1
    return merged_section_ids_map
```
You will get the mapping from the previous sections to the new ones and the previous sections can be accessed via `m.annotations`.

**Comment by alexsavulescu** [comment]
FYI: I had some issues with this branch because I was going back and forth from immutable to mutable (since some data is only accessible through the mutable API - e.g. section_types). 

So to cut things short I created another branch that simply doesn't do sanitisation whatsoever. Available here:
* https://github.com/BlueBrain/MorphIO/tree/unifurcation

Will work with that for the time being.

**Comment by asanin-epfl** [comment]
There is also a feature that sanitization does not work on h5 morphologies prior the latest 2.3.8 version. With 2.3.7 you can load h5 morphology and it won't be sanitized. The PR for that is https://github.com/BlueBrain/MorphIO/pull/181.

**Comment by matz-e** [comment]
This should really have been an opt-in change, IMO. I'm still fixing fallout from this in our checks and unit tests. Rather than changing behavior for old circuits and morphologies, couldn't we have just generated "proper" ones going forward, with an option to read in old morphologies without the unifurcations?

**Comment by alexsavulescu** [comment]
@mgeplf @matz-e, do you think it is (temporarily) worth having this? If yes, change would be fairly straightforward (sanitization opt-out - spack driven). If not, we can close this ticket.

cc: @wizmer

**Comment by alexsavulescu** [comment]
To be resurrected if needed.
